apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.name" . }}
spec:
  selector:    
    {{- include "myapp.labels" . | indent 4 }}
  type: {{ .Values.myapp.service.type }}
  ports:
    - protocol: {{ .Values.myapp.service.protocol }}
      targetPort: {{ .Values.myapp.service.targetport }}
      port: {{ .Values.myapp.service.port }}
